/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    articles: Article;
    achievements: Achievement;
    certificates: Certificate;
    media: Media;
    'contact-submissions': ContactSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    achievements: AchievementsSelect<false> | AchievementsSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    home: Home;
    about: About;
    contact: Contact;
    'projects-page': ProjectsPage;
    'writing-page': WritingPage;
    'achievements-page': AchievementsPage;
    'certificates-page': CertificatesPage;
    'project-page': ProjectPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    'projects-page': ProjectsPageSelect<false> | ProjectsPageSelect<true>;
    'writing-page': WritingPageSelect<false> | WritingPageSelect<true>;
    'achievements-page': AchievementsPageSelect<false> | AchievementsPageSelect<true>;
    'certificates-page': CertificatesPageSelect<false> | CertificatesPageSelect<true>;
    'project-page': ProjectPageSelect<false> | ProjectPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Products, systems, robots & experiments — the things I build.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  name: string;
  tagline: string;
  role: string;
  type: 'product' | 'company' | 'robotics' | 'research';
  year: string;
  /**
   * e.g. Active, Shipped, Ongoing
   */
  status: string;
  /**
   * Card-level + intro paragraph.
   */
  summary: string;
  /**
   * Card / case-study hero. Image optional; label+caption are the text placeholder shown until an image is added.
   */
  cover?: {
    label?: string | null;
    caption?: string | null;
    image?: (string | null) | Media;
  };
  /**
   * Tech stack chips.
   */
  stack?: string[] | null;
  /**
   * Key numbers shown on the card / case study.
   */
  metrics?:
    | {
        label: string;
        value: string;
        /**
         * Feature this metric as the headline "proof" stat on the case study. First proof wins; falls back to the first metric.
         */
        proof?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Case study · the vision.
   */
  vision: string;
  /**
   * Case study · the problem.
   */
  problem: string;
  /**
   * Case study · how it was built (bullet list).
   */
  build?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Case study · the outcome.
   */
  outcome: string;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        label?: string | null;
        caption?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Surface on the homepage & pin to the top of the list.
   */
  featured?: boolean | null;
  /**
   * Build / ship date. Drives the "Recent" view. Falls back to the Year field when blank.
   */
  date?: string | null;
  /**
   * Manual / curated sort. Lower shows first.
   */
  order?: number | null;
  /**
   * URL segment. Leave blank to auto-generate from the title/name.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alt text for accessibility (images). Leave blank for non-image files like the CV.
   */
  alt?: string | null;
  /**
   * Optional caption.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Essays & notes on building, engineering and robotics.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  title: string;
  /**
   * Card + meta description.
   */
  excerpt: string;
  category: 'building' | 'engineering' | 'robotics' | 'essays';
  /**
   * e.g. "8 min"
   */
  readTime: string;
  date: string;
  /**
   * Optional display label, e.g. "Mar 2026". Auto-derived from date if blank.
   */
  dateLabel?: string | null;
  tags?: string[] | null;
  cover?: {
    label?: string | null;
    caption?: string | null;
    image?: (string | null) | Media;
  };
  body: (
    | {
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'paragraph';
      }
    | {
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heading';
      }
    | {
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
  )[];
  featured?: boolean | null;
  /**
   * URL segment. Leave blank to auto-generate from the title/name.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Awards, competitions, leadership & milestones — the timeline.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: string;
  title: string;
  organization: string;
  date: string;
  /**
   * Display label, e.g. "August 2024" or "2024 — Present".
   */
  dateLabel?: string | null;
  type: 'award' | 'competition' | 'leadership' | 'milestone';
  description: string;
  /**
   * Optional external link.
   */
  link?: string | null;
  featured?: boolean | null;
  /**
   * Manual override; otherwise sorted by date (newest first).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Professional credentials & courses.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: string;
  title: string;
  issuer: string;
  date: string;
  /**
   * Display label, e.g. "Jun 2024".
   */
  dateLabel?: string | null;
  credentialId: string;
  skills?: string[] | null;
  /**
   * Drives the discipline filter on the certificates page.
   */
  discipline?: ('Cloud' | 'AI' | 'Robotics' | 'Web') | null;
  /**
   * Surface this credential on the homepage.
   */
  featured?: boolean | null;
  /**
   * Stable identifier used for discipline grouping on the frontend (e.g. "aws-ccp").
   */
  key?: string | null;
  /**
   * Manual override; otherwise sorted by date (newest first).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages sent through the contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  message: string;
  meta?: {
    submittedFrom?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'achievements';
        value: string | Achievement;
      } | null)
    | ({
        relationTo: 'certificates';
        value: string | Certificate;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  role?: T;
  type?: T;
  year?: T;
  status?: T;
  summary?: T;
  cover?:
    | T
    | {
        label?: T;
        caption?: T;
        image?: T;
      };
  stack?: T;
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        proof?: T;
        id?: T;
      };
  vision?: T;
  problem?: T;
  build?:
    | T
    | {
        point?: T;
        id?: T;
      };
  outcome?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        label?: T;
        caption?: T;
        image?: T;
        id?: T;
      };
  featured?: T;
  date?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  category?: T;
  readTime?: T;
  date?: T;
  dateLabel?: T;
  tags?: T;
  cover?:
    | T
    | {
        label?: T;
        caption?: T;
        image?: T;
      };
  body?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  featured?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  title?: T;
  organization?: T;
  date?: T;
  dateLabel?: T;
  type?: T;
  description?: T;
  link?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  title?: T;
  issuer?: T;
  date?: T;
  dateLabel?: T;
  credentialId?: T;
  skills?: T;
  discipline?: T;
  featured?: T;
  key?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  meta?:
    | T
    | {
        submittedFrom?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Name, links, navigation, footer, 404 and SEO defaults used across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * Full name, e.g. "Muztahid Rahman".
   */
  name: string;
  /**
   * First name / wordmark.
   */
  shortName: string;
  role: string;
  location: string;
  tagline: string;
  availability?: string | null;
  email: string;
  github: string;
  linkedin: string;
  /**
   * Primary navigation links (nav + footer).
   */
  nav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footer?: {
    /**
     * e.g. "Let’s build".
     */
    eyebrow?: string | null;
    /**
     * Big CTA headline.
     */
    heading?: string | null;
    /**
     * Italicised word within the heading.
     */
    headingAccent?: string | null;
    /**
     * Primary CTA label, e.g. "Start a conversation".
     */
    ctaLabel?: string | null;
    /**
     * Primary CTA link, e.g. "/contact".
     */
    ctaHref?: string | null;
    /**
     * Sitemap column label, e.g. "Explore".
     */
    exploreLabel?: string | null;
    /**
     * Social column label, e.g. "Connect".
     */
    connectLabel?: string | null;
    /**
     * After "© {year} {name}.", e.g. "Built to last.".
     */
    copyrightSuffix?: string | null;
    /**
     * Small colophon line, e.g. "Next.js · GSAP · Lenis".
     */
    bottomNote?: string | null;
    /**
     * e.g. "Back to top".
     */
    backToTopLabel?: string | null;
  };
  notFound?: {
    /**
     * Handwritten line, e.g. "lost the thread".
     */
    eyebrow?: string | null;
    /**
     * Big number / title, e.g. "404".
     */
    title?: string | null;
    body?: string | null;
    /**
     * e.g. "Back home".
     */
    homeLabel?: string | null;
    /**
     * e.g. "See the projects".
     */
    projectsLabel?: string | null;
  };
  /**
   * Default SEO / social description.
   */
  metaDescription: string;
  /**
   * Canonical site URL (used for metadataBase / OG). e.g. "https://muztahid.dev".
   */
  siteUrl?: string | null;
  /**
   * Fallback Open Graph / social share image.
   */
  defaultOgImage?: (string | null) | Media;
  /**
   * Academic CV (PDF) served by the download CTA.
   */
  cvFile?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The landing page — hero, manifesto, section headers, marquee, now and stats.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  eyebrow: string;
  /**
   * Each row is one line of the big headline.
   */
  headline: {
    line: string;
    id?: string | null;
  }[];
  /**
   * A word within the headline to italicise (must match exactly).
   */
  headlineAccent?: string | null;
  /**
   * Small handwritten accent line.
   */
  script?: string | null;
  lede: string;
  /**
   * Hero portrait image. Falls back to a text placeholder when empty.
   */
  heroPortrait?: (string | null) | Media;
  /**
   * Caption shown over the portrait, e.g. "Engineer · Dhaka".
   */
  heroCaption?: string | null;
  /**
   * Small handwritten badge under the portrait, e.g. "est. 2021".
   */
  heroBadge?: string | null;
  primaryCta: {
    label: string;
    href: string;
  };
  secondaryCta: {
    label: string;
    href: string;
  };
  /**
   * The "premise" block below the marquee.
   */
  manifesto?: {
    eyebrow?: string | null;
    /**
     * The large manifesto statement.
     */
    heading?: string | null;
    /**
     * A word within the heading to italicise (must match exactly).
     */
    headingAccent?: string | null;
    body?: string | null;
    /**
     * Label above the "now" list, e.g. "currently".
     */
    nowLabel?: string | null;
  };
  projectsSection?: {
    eyebrow?: string | null;
    headingLineOne?: string | null;
    /**
     * Italicised second line.
     */
    headingLineTwo?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  writingSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    /**
     * Per-row "Read" label.
     */
    itemCtaLabel?: string | null;
  };
  certificatesSection?: {
    eyebrow?: string | null;
    headingLineOne?: string | null;
    /**
     * Italicised second line.
     */
    headingLineTwo?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  achievementsSection?: {
    eyebrow?: string | null;
    headingLineOne?: string | null;
    /**
     * Italicised second line.
     */
    headingLineTwo?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  /**
   * Scrolling list of org / project names.
   */
  marquee?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * "What I am doing now" rows.
   */
  now?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Eyebrow above the stats grid, e.g. "By the numbers".
   */
  statsEyebrow?: string | null;
  stats?:
    | {
        value: number;
        /**
         * e.g. "+"
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The story — narrative, philosophy, values and journey.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: string;
  eyebrow: string;
  /**
   * The big hero headline — one row per line. The last line is italicised.
   */
  headlineLines?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Word(s) in the last headline line to italicise.
   */
  headlineAccent?: string | null;
  /**
   * Plain-text title used for SEO / fallback.
   */
  title: string;
  intro: string;
  portrait?: {
    label?: string | null;
    caption?: string | null;
    image?: (string | null) | Media;
  };
  /**
   * Handwritten signature beside the portrait.
   */
  signature?: string | null;
  /**
   * Handwritten pull-line after the first paragraph.
   */
  narrativeSignature?: string | null;
  narrative: {
    text: string;
    id?: string | null;
  }[];
  /**
   * Eyebrow above the pull-quote, e.g. "Philosophy".
   */
  philosophyEyebrow?: string | null;
  philosophy: {
    quote: string;
    body: string;
  };
  /**
   * Eyebrow above the values grid, e.g. "What I build by".
   */
  valuesEyebrow?: string | null;
  /**
   * Intro sentence above the values grid.
   */
  valuesIntro?: string | null;
  values?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Eyebrow above the timeline, e.g. "The path so far".
   */
  journeyEyebrow?: string | null;
  /**
   * Intro sentence beside the timeline eyebrow.
   */
  journeyIntro?: string | null;
  journey?:
    | {
        year: string;
        title: string;
        detail: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Eyebrow above the closing statement, e.g. "What’s next".
   */
  nextEyebrow?: string | null;
  /**
   * Closing "what is next" paragraph.
   */
  next: string;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Browser tab / search title. Defaults to "Story".
   */
  metaTitle?: string | null;
  /**
   * Search / social description. Falls back to the intro.
   */
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contact page heading, blurb, invitation, form copy and the list of channels.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: string;
  eyebrow: string;
  title: string;
  /**
   * A word within the title to italicise (must appear in the title exactly).
   */
  titleAccent?: string | null;
  blurb: string;
  /**
   * e.g. "Replies within 48 hours".
   */
  replyTime?: string | null;
  invitation?: {
    /**
     * e.g. "Say hello".
     */
    eyebrow?: string | null;
    /**
     * Handwritten invitation line.
     */
    script?: string | null;
    body?: string | null;
  };
  form?: {
    /**
     * e.g. "Send a note".
     */
    eyebrow?: string | null;
    nameLabel?: string | null;
    namePlaceholder?: string | null;
    emailLabel?: string | null;
    emailPlaceholder?: string | null;
    messageLabel?: string | null;
    messagePlaceholder?: string | null;
    submitLabel?: string | null;
    sendingLabel?: string | null;
    /**
     * Handwritten note beside the submit button.
     */
    footnote?: string | null;
  };
  channels?:
    | {
        label: string;
        value: string;
        /**
         * Optional link (mailto:, https:, ...).
         */
        href?: string | null;
        /**
         * Optional brand icon shown beside the value.
         */
        icon?: ('none' | 'github' | 'linkedin') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Confirmation shown after a message is sent. Use {name} for the sender’s first name.
   */
  success?: {
    script?: string | null;
    heading?: string | null;
    /**
     * Italicised part of the heading.
     */
    headingAccent?: string | null;
    /**
     * Use {name} to insert the sender’s first name.
     */
    body?: string | null;
    /**
     * e.g. "Send another".
     */
    ctaLabel?: string | null;
  };
  /**
   * Client-side validation messages.
   */
  errorMessages?: {
    nameRequired?: string | null;
    emailRequired?: string | null;
    emailInvalid?: string | null;
    messageRequired?: string | null;
    submitFailed?: string | null;
  };
  /**
   * Browser tab / search title. Defaults to "Contact".
   */
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero copy, control labels and empty-state for the /projects list page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page".
 */
export interface ProjectsPage {
  id: string;
  eyebrow?: string | null;
  headlineLineOne?: string | null;
  /**
   * Italicised line.
   */
  headlineLineTwo?: string | null;
  intro?: string | null;
  /**
   * Noun after the count, e.g. "projects".
   */
  countNoun?: string | null;
  /**
   * e.g. "View".
   */
  viewLabel?: string | null;
  curatedLabel?: string | null;
  recentLabel?: string | null;
  featuredLabel?: string | null;
  /**
   * Type filter "All".
   */
  allLabel?: string | null;
  /**
   * Between counts, e.g. "of".
   */
  ofLabel?: string | null;
  /**
   * Handwritten "featured" badge on rows.
   */
  featuredBadge?: string | null;
  /**
   * Per-row CTA, e.g. "View project".
   */
  rowCtaLabel?: string | null;
  /**
   * e.g. "nothing here… yet".
   */
  emptyScript?: string | null;
  emptyMessageFeatured?: string | null;
  emptyMessageDefault?: string | null;
  emptyCtaLabel?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero, featured and archive copy for the /writing list page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writing-page".
 */
export interface WritingPage {
  id: string;
  eyebrow?: string | null;
  headlineLineOne?: string | null;
  /**
   * Italicised line.
   */
  headlineLineTwo?: string | null;
  lede?: string | null;
  /**
   * Phrase within the lede to emphasise (must match exactly).
   */
  ledeHighlight?: string | null;
  /**
   * Handwritten line, e.g. "from the desk".
   */
  signature?: string | null;
  /**
   * Trailing descriptor after the count.
   */
  descriptor?: string | null;
  /**
   * e.g. "Featured".
   */
  featuredEyebrow?: string | null;
  /**
   * e.g. "Read the essay".
   */
  featuredCtaLabel?: string | null;
  /**
   * e.g. "The archive".
   */
  archiveEyebrow?: string | null;
  archiveHeading?: string | null;
  /**
   * Italicised part of the archive heading.
   */
  archiveHeadingAccent?: string | null;
  /**
   * Category filter "All".
   */
  allLabel?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero, stats labels, highlights, full-record and closing copy for /achievements.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements-page".
 */
export interface AchievementsPage {
  id: string;
  eyebrow?: string | null;
  headingLineOne?: string | null;
  /**
   * Italicised line.
   */
  headingLineTwo?: string | null;
  lede?: string | null;
  /**
   * Handwritten line beside the lede.
   */
  signature?: string | null;
  /**
   * Labels for the three derived stat counts (order matters: total, awards+competitions, leadership).
   */
  statLabels?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  highlightsEyebrow?: string | null;
  highlightsHeading?: string | null;
  /**
   * Italicised word.
   */
  highlightsHeadingAccent?: string | null;
  highlightsBlurb?: string | null;
  /**
   * Handwritten label on the lead highlight, e.g. "the gold standard".
   */
  leadScript?: string | null;
  recordEyebrow?: string | null;
  recordHeading?: string | null;
  /**
   * Italicised word.
   */
  recordHeadingAccent?: string | null;
  /**
   * Per-entry external link label, e.g. "Read more".
   */
  linkLabel?: string | null;
  closingText?: string | null;
  /**
   * Italicised part.
   */
  closingTextAccent?: string | null;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero, filter labels, disciplines and closing copy for /certificates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates-page".
 */
export interface CertificatesPage {
  id: string;
  eyebrow?: string | null;
  /**
   * Before the italic word, e.g. "Always ".
   */
  headlinePrefix?: string | null;
  /**
   * Italic word, e.g. "sharpening".
   */
  headlineAccent?: string | null;
  /**
   * After the italic word, e.g. " the craft.".
   */
  headlineSuffix?: string | null;
  lede?: string | null;
  /**
   * Phrase within the lede to emphasise (must match exactly).
   */
  ledeHighlight?: string | null;
  /**
   * Handwritten line, e.g. "still a student".
   */
  signature?: string | null;
  /**
   * e.g. "Browse".
   */
  filterEyebrow?: string | null;
  filterDescription?: string | null;
  /**
   * First filter chip, e.g. "All".
   */
  allLabel?: string | null;
  /**
   * Discipline filter chips (must match the Discipline values on certificates). "All" is added automatically.
   */
  disciplines?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  closingEyebrow?: string | null;
  closingHeadingPrefix?: string | null;
  /**
   * Italicised word.
   */
  closingHeadingAccent?: string | null;
  closingHeadingSuffix?: string | null;
  closingBody?: string | null;
  closingCtaLabel?: string | null;
  closingCtaHref?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Shared section labels & pager copy rendered on every project case study.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-page".
 */
export interface ProjectPage {
  id: string;
  caseStudy?: {
    visionLabel?: string | null;
    problemLabel?: string | null;
    buildLabel?: string | null;
    outcomeLabel?: string | null;
    galleryLabel?: string | null;
    /**
     * e.g. "built with".
     */
    builtWithLabel?: string | null;
    /**
     * e.g. "the proof".
     */
    proofLabel?: string | null;
  };
  pager?: {
    /**
     * e.g. "Previous project".
     */
    prevLabel?: string | null;
    /**
     * e.g. "Next project".
     */
    nextLabel?: string | null;
    /**
     * End-cap, e.g. "That’s the latest".
     */
    latestLabel?: string | null;
    /**
     * End-cap, e.g. "Back to the start".
     */
    startLabel?: string | null;
    /**
     * e.g. "All projects".
     */
    allProjectsLabel?: string | null;
    /**
     * e.g. "the full body of work".
     */
    allProjectsScript?: string | null;
    /**
     * Back link, e.g. "All projects".
     */
    backLinkLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  role?: T;
  location?: T;
  tagline?: T;
  availability?: T;
  email?: T;
  github?: T;
  linkedin?: T;
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        headingAccent?: T;
        ctaLabel?: T;
        ctaHref?: T;
        exploreLabel?: T;
        connectLabel?: T;
        copyrightSuffix?: T;
        bottomNote?: T;
        backToTopLabel?: T;
      };
  notFound?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        homeLabel?: T;
        projectsLabel?: T;
      };
  metaDescription?: T;
  siteUrl?: T;
  defaultOgImage?: T;
  cvFile?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?:
    | T
    | {
        line?: T;
        id?: T;
      };
  headlineAccent?: T;
  script?: T;
  lede?: T;
  heroPortrait?: T;
  heroCaption?: T;
  heroBadge?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  manifesto?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        headingAccent?: T;
        body?: T;
        nowLabel?: T;
      };
  projectsSection?:
    | T
    | {
        eyebrow?: T;
        headingLineOne?: T;
        headingLineTwo?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  writingSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        ctaLabel?: T;
        ctaHref?: T;
        itemCtaLabel?: T;
      };
  certificatesSection?:
    | T
    | {
        eyebrow?: T;
        headingLineOne?: T;
        headingLineTwo?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  achievementsSection?:
    | T
    | {
        eyebrow?: T;
        headingLineOne?: T;
        headingLineTwo?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  marquee?:
    | T
    | {
        text?: T;
        id?: T;
      };
  now?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  statsEyebrow?: T;
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  eyebrow?: T;
  headlineLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  headlineAccent?: T;
  title?: T;
  intro?: T;
  portrait?:
    | T
    | {
        label?: T;
        caption?: T;
        image?: T;
      };
  signature?: T;
  narrativeSignature?: T;
  narrative?:
    | T
    | {
        text?: T;
        id?: T;
      };
  philosophyEyebrow?: T;
  philosophy?:
    | T
    | {
        quote?: T;
        body?: T;
      };
  valuesEyebrow?: T;
  valuesIntro?: T;
  values?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  journeyEyebrow?: T;
  journeyIntro?: T;
  journey?:
    | T
    | {
        year?: T;
        title?: T;
        detail?: T;
        id?: T;
      };
  nextEyebrow?: T;
  next?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleAccent?: T;
  blurb?: T;
  replyTime?: T;
  invitation?:
    | T
    | {
        eyebrow?: T;
        script?: T;
        body?: T;
      };
  form?:
    | T
    | {
        eyebrow?: T;
        nameLabel?: T;
        namePlaceholder?: T;
        emailLabel?: T;
        emailPlaceholder?: T;
        messageLabel?: T;
        messagePlaceholder?: T;
        submitLabel?: T;
        sendingLabel?: T;
        footnote?: T;
      };
  channels?:
    | T
    | {
        label?: T;
        value?: T;
        href?: T;
        icon?: T;
        id?: T;
      };
  success?:
    | T
    | {
        script?: T;
        heading?: T;
        headingAccent?: T;
        body?: T;
        ctaLabel?: T;
      };
  errorMessages?:
    | T
    | {
        nameRequired?: T;
        emailRequired?: T;
        emailInvalid?: T;
        messageRequired?: T;
        submitFailed?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page_select".
 */
export interface ProjectsPageSelect<T extends boolean = true> {
  eyebrow?: T;
  headlineLineOne?: T;
  headlineLineTwo?: T;
  intro?: T;
  countNoun?: T;
  viewLabel?: T;
  curatedLabel?: T;
  recentLabel?: T;
  featuredLabel?: T;
  allLabel?: T;
  ofLabel?: T;
  featuredBadge?: T;
  rowCtaLabel?: T;
  emptyScript?: T;
  emptyMessageFeatured?: T;
  emptyMessageDefault?: T;
  emptyCtaLabel?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "writing-page_select".
 */
export interface WritingPageSelect<T extends boolean = true> {
  eyebrow?: T;
  headlineLineOne?: T;
  headlineLineTwo?: T;
  lede?: T;
  ledeHighlight?: T;
  signature?: T;
  descriptor?: T;
  featuredEyebrow?: T;
  featuredCtaLabel?: T;
  archiveEyebrow?: T;
  archiveHeading?: T;
  archiveHeadingAccent?: T;
  allLabel?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements-page_select".
 */
export interface AchievementsPageSelect<T extends boolean = true> {
  eyebrow?: T;
  headingLineOne?: T;
  headingLineTwo?: T;
  lede?: T;
  signature?: T;
  statLabels?:
    | T
    | {
        label?: T;
        id?: T;
      };
  highlightsEyebrow?: T;
  highlightsHeading?: T;
  highlightsHeadingAccent?: T;
  highlightsBlurb?: T;
  leadScript?: T;
  recordEyebrow?: T;
  recordHeading?: T;
  recordHeadingAccent?: T;
  linkLabel?: T;
  closingText?: T;
  closingTextAccent?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates-page_select".
 */
export interface CertificatesPageSelect<T extends boolean = true> {
  eyebrow?: T;
  headlinePrefix?: T;
  headlineAccent?: T;
  headlineSuffix?: T;
  lede?: T;
  ledeHighlight?: T;
  signature?: T;
  filterEyebrow?: T;
  filterDescription?: T;
  allLabel?: T;
  disciplines?:
    | T
    | {
        label?: T;
        id?: T;
      };
  closingEyebrow?: T;
  closingHeadingPrefix?: T;
  closingHeadingAccent?: T;
  closingHeadingSuffix?: T;
  closingBody?: T;
  closingCtaLabel?: T;
  closingCtaHref?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-page_select".
 */
export interface ProjectPageSelect<T extends boolean = true> {
  caseStudy?:
    | T
    | {
        visionLabel?: T;
        problemLabel?: T;
        buildLabel?: T;
        outcomeLabel?: T;
        galleryLabel?: T;
        builtWithLabel?: T;
        proofLabel?: T;
      };
  pager?:
    | T
    | {
        prevLabel?: T;
        nextLabel?: T;
        latestLabel?: T;
        startLabel?: T;
        allProjectsLabel?: T;
        allProjectsScript?: T;
        backLinkLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}